spring:
  application:
    name: course-manage

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/course_manage}
    username:  ${SPRING_DATASOURCE_ROOT:root}
    password:  ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name:  ${SPRING_DATASOURCE_NAME:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "backend.skillgo@gmail.com"
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
server:
  port: 8080
  servlet:
    context-path:

Jwt:
  signerKey: "Hj1qok1EhD77jwWz8aUuSXmCN4VC+WpMFDTqlwD73qkgTlKEIzqH2re9g/S06Vzc"
file:
  root-path: C:\Users\HP\OneDrive\Documents\2023-2024\Theme02\Course02Theme\html.themegenix.com\skillgro\assets\img
